accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

tasks/urls.py
from django.urls import path


from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
)


urlpatterns = [
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("packages/", include("packages.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "packages.Package",
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return (
            f"{self.name} assigned to [ {self.assignee} ] in _{self.project}_"
        )

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

tasks/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from tasks.models import Task


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/mine.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        task = form.save(commit=False)
        task.user = self.request.user
        task.save()
        form.save_m2m()
        return redirect("show_project", pk=task.project.id)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/complete.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

accounts/templates/base.html
{% load static %}
{% load markdownify %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/pretty.css' %}">
        <title>Tracker</title>
    </head>
    <body>
        <header>
            <nav class="navbar">
                {%if user.is_authenticated %}
                    <a href="{% url 'home' %}">Project Lists</a>
                    <a href="{% url 'show_my_tasks' %}">Task Lists</a>
                    <a href="{% url 'create_project' %}">New Project</a>
                    <a href="{% url 'create_task' %}">New Task</a>
                    {% if user.is_superuser %}
                        <a href="{% url 'admin:index' %}">Admin</a>
                    {% endif %}
                    <a href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                    <a href="{% url 'signup' %}">Sign up!</a>
                {% endif %}
            </nav>
        </header>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

tasks/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Create a new task</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
{% endblock content %}

tasks/templates/tasks/mine.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div>
        <h1>My Tasks</h1>
        {% if task_list|length <= 0 %}
            <p>You have no tasks</p>
        {% else %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Is completed</th>
                    </tr>
                </thead>
                <tb>
                    {% for task in task_list %}
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.start_date|date:"M d, Y" }}</td>
                            <td>{{ task.due_date|date:"M d, Y" }}</td>
                            <td>
                                {% if task.is_completed %}
                                    done
                                {% else %}
                                    <form method="post" action="{% url 'complete_task' task.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tb>
            </table>
        {% endif %}
    </div>
{% endblock content %}